(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(global-set-key (kbd "<f5>") 'bookmark-jump)
(global-set-key (kbd "<f6>") 'bookmark-set)
(global-set-key (kbd "<f12>") 'org-agenda)
(global-set-key (kbd "<f9> I") 'bh/punch-in);(global-set-key (kbd "<f9> SPC") 'bh/clock-in-select-task);(global-set-key (kbd "<f11>") 'org-clock-goto)
(global-set-key (kbd "C-<f11>") 'org-clock-in)
(global-set-key (kbd "<f7>") 'bh/set-truncate-lines)
(global-set-key (kbd "<f9> v") 'visible-mode)
(global-set-key (kbd "C-x n r") 'narrow-to-region)
(global-set-key (kbd "M-<f9>") 'org-toggle-inline-images)
(global-set-key (kbd "<f9> c") 'calendar)
(global-set-key (kbd "<f9> h") 'bh/hide-other)
(global-set-key (kbd "<f9> n") 'bh/toggle-next-task-display)
(global-set-key (kbd "C-c c") 'org-capture)
