(provide 'twl-mew)

;;装载Mew
(add-to-list 'load-path "d:/Sync/CloudStation/App/Emacs/.emacs.d/lisp/mew-lisp/")
(autoload 'mew "mew" nil t)
(autoload 'mew-send "mew" nil t)
(setq mew-icon-directory "d:/Sync/CloudStation/App/Emacs/.emacs.d/lisp/mew-lisp/etc")
(setq mew-use-cached-passwd t)
(if (boundp 'read-mail-command)
    (setq read-mail-command 'mew))
(autoload 'mew-user-agent-compose "mew" nil t)
(if (boundp 'mail-user-agent)
    (setq mail-user-agent 'mew-user-agent))
(if (fboundp 'define-mail-user-agent)
    (define-mail-user-agent
    'mew-user-agent
    'mew-user-agent-compose
    'mew-draft-send-message
    'mew-draft-kill
    'mew-send-hook))
(setq mew-pop-size 0)
(setq mew-smtp-auth-list nil)
(setq toolbar-mail-reader 'Mew)
(set-default 'mew-decode-quoted 't)
(when (boundp 'utf-translate-cjk)
    (setq utf-translate-cjk t)
    (custom-set-variables
     '(utf-translate-cjk t)))
(if (fboundp 'utf-translate-cjk-mode)
    (utf-translate-cjk-mode 1))
;;(require 'mew-w3m) ;需要w3m支持，看html邮件
(setq mew-config-alist '(
  ("default"
    ("name" . "taowl2003@sina.com")
    ("user" . "taowl2003")
    ("smtp-server" . "smtp.sina.com")
    ("smtp-port" . "25")
    ("pop-server" . "pop.sina.com")
    ("pop-port" . "110")
    ("smtp-user" . "taowl2003")
    ("pop-user" . "taowl2003")
    ("mail-domain" . "sina.com")
    ("mailbox-type" . pop)
    ("pop-delete" . nil)
    ("pop-size" . 0) 
    ("pop-auth" . pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
    )
  ("gmail"
    ("name"         .  "taowl2003@gmail.com")
    ("user"         .  "taowl2003")
    ("smtp-server"  .  "smtp.gmail.com")
    ("smtp-port"    .  "465")
    ("imap-server"   .  "imap.gmail.com")
    ("imap-port"     .  "993")
    ;;("pop-server" . "pop.gmail.com")
    ;;("pop-port" . "995")
    ("smtp-user"    .  "taowl2003@gmail.com")
    ("imap-user"     .  "taowl2003@gmail.com")
    ;;("pop-user"     .  "taowl2003@gmail.com")
    ("mail-domain"  .  "gmail.com")
    ("mailbox-type" .  imap)
    ;;("mailbox-type" .  pop)
    ("proto" . "%")
    ("imap-delete" . nil)
    ;;("pop-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
    ;;("pop-size" . 0) 
    ;;("pop-auth"     .  pass)
    ;;("pop-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("gmail"
    ("name"         .  "taowl2003@gmail.com")
    ("user"         .  "taowl2003")
    ("smtp-server"  .  "smtp.gmail.com")
    ("smtp-port"    .  "465")
    ("imap-server"   .  "imap.gmail.com")
    ("imap-port"     .  "993")
    ;;("pop-server" . "pop.gmail.com")
    ;;("pop-port" . "995")
    ("smtp-user"    .  "taowl2003@gmail.com")
    ("imap-user"     .  "taowl2003@gmail.com")
    ;;("pop-user"     .  "taowl2003@gmail.com")
    ("mail-domain"  .  "gmail.com")
    ("mailbox-type" .  imap)
    ;;("mailbox-type" .  pop)
    ("proto" . "%")
    ("imap-delete" . nil)
    ;;("pop-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
    ;;("pop-size" . 0) 
    ;;("pop-auth"     .  pass)
    ;;("pop-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("gmail-pop"
    ("name"         .  "taowl2003@gmail.com")
    ("user"         .  "taowl2003")
    ("smtp-server"  .  "smtp.gmail.com")
    ("smtp-port"    .  "465")
    ("pop-server" . "pop.gmail.com")
    ("pop-port" . "995")
    ("smtp-user"    .  "taowl2003@gmail.com")
    ("pop-user"     .  "taowl2003@gmail.com")
    ("mail-domain"  .  "gmail.com")
    ("mailbox-type" .  pop)
    ("pop-delete" . nil)
    ("pop-size" . 0) 
    ("pop-auth"     .  pass)
    ("pop-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("126"
    ("name"         .  "taowl2003@126.com")
    ("user"         .  "taowl2003")
    ("smtp-server"  .  "smtp.126.com")
    ("smtp-port"    .  "25")
    ("imap-server"   .  "imap.126.com")
    ("imap-port"     .  "143")
    ;;("pop-server" . "pop.gmail.com")
    ;;("pop-port" . "995")
    ("smtp-user"    .  "taowl2003@126.com")
    ("imap-user"     .  "taowl2003@126.com")
    ;;("pop-user"     .  "taowl2003@gmail.com")
    ("mail-domain"  .  "126.com")
    ("mailbox-type" .  imap)
    ;;("mailbox-type" .  pop)
    ("proto" . "%")
    ("imap-delete" . nil)
    ;;("pop-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
    ;;("pop-size" . 0) 
    ;;("pop-auth"     .  pass)
    ;;("pop-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("163"
    ("name"         .  "taowl2003@163.com")
    ("user"         .  "taowl2003")
    ("smtp-server"  .  "smtp.163.com")
    ("smtp-port"    .  "25")
    ("imap-server"   .  "imap.163.com")
    ("imap-port"     .  "143")
    ;;("pop-server" . "pop.gmail.com")
    ;;("pop-port" . "995")
    ("smtp-user"    .  "taowl2003@163.com")
    ("imap-user"     .  "taowl2003@163.com")
    ;;("pop-user"     .  "taowl2003@gmail.com")
    ("mail-domain"  .  "163.com")
    ("mailbox-type" .  imap)
    ;;("mailbox-type" .  pop)
    ("proto" . "%")
    ("imap-delete" . nil)
    ;;("pop-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
    ;;("pop-size" . 0) 
    ;;("pop-auth"     .  pass)
    ;;("pop-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("whu"
    ("name"         .  "taoweiliang@whu.edu.cn")
    ("user"         .  "taoweiliang")
    ("smtp-server"  .  "smtp.whu.edu.cn")
    ("smtp-port"    .  "25")
    ("imap-server"   .  "whu.edu.cn")
    ("imap-port"     .  "993")
    ("smtp-user"    .  "taoweiliang@whu.edu.cn")
    ("imap-user"     .  "taoweiliang@whu.edu.cn")
    ("mail-domain"  .  "whu.edu.cn")
    ("mailbox-type" .  imap)
    ("proto" . "%")
    ("imap-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("qq498"
    ("name"         .  "498756902@qq.com")
    ("user"         .  "498756902")
    ("smtp-server"  .  "smtp.qq.com")
    ("smtp-port"    .  "465")
    ("imap-server"   .  "imap.qq.com")
    ("imap-port"     .  "993")
    ("smtp-user"    .  "498756902@qq.com")
    ("imap-user"     .  "498756902@qq.com")
    ("mail-domain"  .  "qq.com")
    ("mailbox-type" .  imap)
    ("proto" . "%")
    ("imap-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("qq545"
    ("name"         .  "545956039@qq.com")
    ("user"         .  "545956039")
    ("smtp-server"  .  "smtp.qq.com")
    ("smtp-port"    .  "465")
    ("imap-server"   .  "imap.qq.com")
    ("imap-port"     .  "993")
    ("smtp-user"    .  "545956039@qq.com")
    ("imap-user"     .  "545956039@qq.com")
    ("mail-domain"  .  "qq.com")
    ("mailbox-type" .  imap)
    ("proto" . "%")
    ("imap-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
  ("189"
    ("name"         .  "18986199069@189.cn")
    ("user"         .  "18986199069")
    ("smtp-server"  .  "smtp.189.cn")
    ("smtp-port"    .  "25")
    ("imap-server"   .  "imap.189.cn")
    ("imap-port"     .  "143")
    ("smtp-user"    .  "18986199069@189.cn")
    ("imap-user"     .  "18986199069@189.cn")
    ("mail-domain"  .  "189.cn")
    ("mailbox-type" .  imap)
    ("proto" . "%")
    ("imap-delete" . nil)
    ("imap-size" . 0) 
    ("imap-auth"     .  pass)
    ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
)
    ))
(setq mew-ssl-verify-level 0)
